### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by westnight** [yh-iro/Keras_TP-GAN#2]
Thanks for sharing your code! I noticed when training LightCNN, you trained 1060 epochs for the first step  but as I konw the MS1M  is a really big dataset, even for the cleaned MS1M. So how long it takes you to finished the first step. Thanks  again for sharing your excellect code.

**Comment by yh-iro** [comment]
I don't remember clearly, but it was not more than a week. Maybe around 5 days for learning MS1M aligned.
