### ISSUE TITLE
how to train the model

### ISSUE THREAD

**Issue by songyy137222** [yh-iro/Keras_TP-GAN#3]
hi，can I known where is the code that you save the generator model. In the tpgan,i can not find the code in the function of train_generator.when i train the tp-gan,i can not find the trained model.

**Comment by yh-iro** [comment]
Please see keras_tpgan/tpgan.py L800. In this line, I called function fit_generator provided by Keras. Generator model is saved in this function.
https://keras.io/models/model/#methods
