### ISSUE TITLE
no face detected

### ISSUE THREAD

**Issue by changgongcheng** [yh-iro/Keras_TP-GAN#4]
Hi, I met some problems. When detect face with +or - 90 degree, it can not be detected. How do you handle this?

**Comment by yh-iro** [comment]
In this time, I trained using train data -60 deg to +60 deg.

**Comment by changgongcheng** [comment]
OK, thanks

**Comment by changgongcheng** [comment]
I am sorry.There is  an another question. Is the five keypoins : left and right eye, nose tip, left and right mouth？ the origin author did not mention

**Comment by yh-iro** [comment]
Yes. Left and right eye, nose tip, and mouth.
